<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WebUIToolkitDefaultTargetFramework)</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WebUIToolkit.DependencyNotices.Npm\WebUIToolkit.DependencyNotices.Npm.csproj" />
  </ItemGroup>
</Project>
