<Project>
  <PropertyGroup>
    <DependencyNoticesEnabled Condition="'$(DependencyNoticesEnabled)' == ''">false</DependencyNoticesEnabled>
    <DependencyNoticesMode Condition="'$(DependencyNoticesMode)' == '' and '$(ContinuousIntegrationBuild)' == 'true'">Verify</DependencyNoticesMode>
    <DependencyNoticesMode Condition="'$(DependencyNoticesMode)' == ''">Generate</DependencyNoticesMode>
    <DependencyNoticesRoot Condition="'$(DependencyNoticesRoot)' == ''">$(MSBuildProjectDirectory)</DependencyNoticesRoot>
    <DependencyNoticesConfig Condition="'$(DependencyNoticesConfig)' == ''">dependency-notices.input.json</DependencyNoticesConfig>
    <DependencyNoticesOutputDirectory Condition="'$(DependencyNoticesOutputDirectory)' == ''">$(MSBuildProjectDirectory)/obj/dependency-notices/</DependencyNoticesOutputDirectory>
    <DependencyNoticesArtifactName Condition="'$(DependencyNoticesArtifactName)' == ''">$(MSBuildProjectName)</DependencyNoticesArtifactName>
    <DependencyNoticesArtifactVersion Condition="'$(DependencyNoticesArtifactVersion)' == ''">$(Version)</DependencyNoticesArtifactVersion>
  </PropertyGroup>
</Project>
