// <auto-generated />
import {
  createSvelteMvvmCommandFacade,
  derivedMvvmCollection,
  derivedMvvmProperty,
  derivedMvvmValidation,
  type SvelteMvvmStore,
} from "@runic-artifex/mvvm-svelte";
import type { CounterContract } from "./counter-contract.g.js";

export function createCounterStores(
  store: SvelteMvvmStore,
  contract: CounterContract,
) {
  const countBinding = derivedMvvmProperty(store, contract.count);
  const stepBinding = derivedMvvmProperty(store, contract.step);
  const stepErrors = derivedMvvmValidation(store, contract.step);
  const historyBinding = derivedMvvmCollection(store, contract.history);
  const summaryBinding = derivedMvvmProperty(store, contract.summary);
  const incrementBinding = createSvelteMvvmCommandFacade(store, contract.increment);
  return {
    contract,
    count: countBinding,
    step: stepBinding,
    stepErrors,
    history: historyBinding,
    summary: summaryBinding,
    increment: incrementBinding,
    dispose() {
      incrementBinding.dispose();
    },
  } as const;
}
