<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WebUIToolkitDefaultTargetFramework)</TargetFramework>
    <WebUIToolkitShippingProject>false</WebUIToolkitShippingProject>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/WebUIToolkit.DependencyNotices.Engine/WebUIToolkit.DependencyNotices.Engine.csproj" />
  </ItemGroup>
</Project>
