<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WebUIToolkitDefaultTargetFramework)</TargetFramework>
    <AssemblyName>WebUIToolkit.MVVM.ReactiveUI.Tests</AssemblyName>
    <RootNamespace>WebUIToolkit.MVVM.ReactiveUI.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/WebUIToolkit.MVVM.ReactiveUI/WebUIToolkit.MVVM.ReactiveUI.csproj" />
    <ProjectReference Include="../../src/WebUIToolkit.MVVM.Build/WebUIToolkit.MVVM.Build.csproj" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators"
                      PrivateAssets="all"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AotSmoke/**/*.cs" />
  </ItemGroup>
</Project>
