// <auto-generated />
#nullable enable

namespace WebUIToolkitStarter;

internal static class CounterContracts
{
    internal static class Counter
    {
        internal const string Name = "webuitoolkitstarter.counter";

        internal static class Members
        {
            internal const int Count = 1;
            internal const int Step = 2;
            internal const int History = 3;
            internal const int Summary = 4;
            internal const int Increment = 10;
        }

        internal static global::WebUIToolkit.MVVM.CommunityToolkit.CommunityToolkitMvvmBindingAdapter<global::WebUIToolkitStarter.CounterViewModel> CreateAdapter(
            global::WebUIToolkitStarter.CounterViewModel model) =>
            new global::WebUIToolkit.MVVM.CommunityToolkit.CommunityToolkitMvvmAdapterBuilder<global::WebUIToolkitStarter.CounterViewModel>(model)
                .BindReadOnlyProperty(
                    Members.Count,
                    "Count",
                    static state => state.Count,
                    global::WebUIToolkitStarter.CounterJsonContext.Default.Int32)
                .BindProperty(
                    Members.Step,
                    "Step",
                    static state => state.Step,
                    static (state, value) => state.Step = value,
                    global::WebUIToolkitStarter.CounterJsonContext.Default.Int32,
                    includeValidation: true)
                .BindCollection(
                    Members.History,
                    "History",
                    static state => state.History,
                    global::WebUIToolkitStarter.CounterJsonContext.Default.Int32)
                .BindReadOnlyProperty(
                    Members.Summary,
                    "Summary",
                    static state => state.Summary,
                    global::WebUIToolkitStarter.CounterJsonContext.Default.String)
                .BindCommand(
                    Members.Increment,
                    "IncrementCommand",
                    static state => state.IncrementCommand)
                .Build();
    }

}
