// <auto-generated />
import {
  MvvmCollection,
  MvvmCommand,
  MvvmCommandWithArgument,
  MvvmProperty,
  MvvmReadonlyProperty,
  type MvvmProjection,
} from "@webuitoolkit/mvvm";

export class CounterContract {
  public static readonly contractName = "webuitoolkitstarter.counter" as const;
  public static readonly memberMetadata = [
    { id: 1, name: "count", sourceMember: "WebUIToolkitStarter.CounterViewModel.Count" },
    { id: 2, name: "step", sourceMember: "WebUIToolkitStarter.CounterViewModel.Step" },
    { id: 3, name: "history", sourceMember: "WebUIToolkitStarter.CounterViewModel.History" },
    { id: 4, name: "summary", sourceMember: "WebUIToolkitStarter.CounterViewModel.Summary" },
    { id: 10, name: "increment", sourceMember: "WebUIToolkitStarter.CounterViewModel.IncrementCommand" },
  ] as const;

  public readonly count;
  public readonly step;
  public readonly history;
  public readonly summary;
  public readonly increment;

  public constructor(projection: MvvmProjection) {
    this.count = new MvvmReadonlyProperty<number>(projection, 1);
    this.step = new MvvmProperty<number>(projection, 2);
    this.history = new MvvmCollection<number>(projection, 3);
    this.summary = new MvvmReadonlyProperty<string>(projection, 4);
    this.increment = new MvvmCommand(projection, 10);
  }
}
