// <auto-generated />
import {
  useVueMvvmCollection,
  useVueMvvmCommandFacade,
  useVueMvvmProperty,
  useVueMvvmValidation,
  type VueMvvmAdapter,
} from "@webuitoolkit/mvvm-vue";
import type { CounterContract } from "./counter-contract.g.js";

export function useCounterBindings(
  contract: CounterContract,
  adapter?: VueMvvmAdapter,
) {
  const countBinding = useVueMvvmProperty(contract.count, adapter);
  const stepBinding = useVueMvvmProperty(contract.step, adapter);
  const stepErrors = useVueMvvmValidation(contract.step, adapter);
  const historyBinding = useVueMvvmCollection(contract.history, adapter);
  const summaryBinding = useVueMvvmProperty(contract.summary, adapter);
  const incrementBinding = useVueMvvmCommandFacade(contract.increment, adapter);
  return {
    contract,
    count: countBinding,
    step: stepBinding,
    stepErrors,
    history: historyBinding,
    summary: summaryBinding,
    increment: incrementBinding,
  } as const;
}
