// <auto-generated />
import {
  useMvvmCollection,
  useMvvmCommandFacade,
  useMvvmProperty,
  useMvvmValidation,
} from "@runic-artifex/mvvm-react";
import type { CounterContract } from "./counter-contract.g.js";

export function useCounterBindings(contract: CounterContract) {
  const countBinding = useMvvmProperty(contract.count);
  const stepBinding = useMvvmProperty(contract.step);
  const stepErrors = useMvvmValidation(contract.step);
  const historyBinding = useMvvmCollection(contract.history);
  const summaryBinding = useMvvmProperty(contract.summary);
  const incrementBinding = useMvvmCommandFacade(contract.increment);
  return {
    contract,
    count: countBinding,
    step: stepBinding,
    stepErrors,
    history: historyBinding,
    summary: summaryBinding,
    increment: incrementBinding,
  } as const;
}
