<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Runic.Application/Runic.Application.csproj" />
    <ProjectReference Include="../../src/Runic.Application.Generators/Runic.Application.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/Runic.Application.Bridge/Runic.Application.Bridge.csproj" />
    <ProjectReference Include="../../src/Runic.Application.Testing/Runic.Application.Testing.csproj" />
  </ItemGroup>
</Project>
