// <auto-generated />
import { inject, type Provider } from "@angular/core";
import { AngularMvvmStore } from "@webuitoolkit/mvvm-angular";
import type { CounterContract } from "./counter-contract.g.js";

export class CounterContractService {
  public readonly count;
  public readonly step;
  public readonly stepErrors;
  public readonly history;
  public readonly summary;
  public readonly increment;

  public constructor(
    public readonly store: AngularMvvmStore,
    public readonly contract: CounterContract,
  ) {
    this.count = store.property(contract.count);
    this.step = store.property(contract.step);
    this.stepErrors = store.validation(contract.step);
    this.history = store.collection(contract.history);
    this.summary = store.property(contract.summary);
    this.increment = store.commandFacade(contract.increment);
  }
}

export function provideCounterContract(
  store: AngularMvvmStore,
  contract: CounterContract,
): readonly Provider[] {
  return [{ provide: CounterContractService, useFactory: () => new CounterContractService(store, contract) }];
}

export function injectCounterContract(): CounterContractService {
  return inject(CounterContractService);
}
