<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>WebUIToolkit.DotNet.WebUIToolkit.Tests</AssemblyName>
    <RootNamespace>WebUIToolkit.DotNet.WebUIToolkit.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../tools/dotnet-webuitoolkit/WebUIToolkit.DotNet.WebUIToolkit.csproj" />
  </ItemGroup>
</Project>
