<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RunicToolkitDefaultTargetFramework)</TargetFramework>
    <AssemblyName>RunicToolkit.MVVM.CommunityToolkit.Tests</AssemblyName>
    <RootNamespace>RunicToolkit.MVVM.CommunityToolkit.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/RunicToolkit.MVVM.CommunityToolkit/RunicToolkit.MVVM.CommunityToolkit.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AotSmoke/**/*.cs" />
    <Compile Remove="PackageConsumer/**/*.cs" />
  </ItemGroup>
</Project>
