<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RunicToolkitDefaultTargetFramework)</TargetFramework>
    <AssemblyName>RunicToolkit.MVVM.BindingCompiler.Tests</AssemblyName>
    <RootNamespace>RunicToolkit.MVVM.BindingCompiler.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tools\RunicToolkit.MVVM.BindingCompiler\RunicToolkit.MVVM.BindingCompiler.csproj" />
  </ItemGroup>
</Project>
