<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WebUIToolkitDefaultTargetFramework)</TargetFramework>
    <AssemblyName>WebUIToolkit.Hosting.CsWebUi.Tests</AssemblyName>
    <RootNamespace>WebUIToolkit.Hosting.CsWebUi.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/WebUIToolkit.Hosting.CsWebUi/WebUIToolkit.Hosting.CsWebUi.csproj" />
  </ItemGroup>
</Project>
