<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>RunicToolkit.Hosting.CsWebUi.NativeE2E</AssemblyName>
    <RootNamespace>RunicToolkit.Hosting.CsWebUi.NativeE2E</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsWebUi" />
    <ProjectReference Include="../../src/RunicToolkit.Hosting.CsWebUi.ApplicationBridge/RunicToolkit.Hosting.CsWebUi.ApplicationBridge.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="www/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
