<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RunicToolkitDefaultTargetFramework)</TargetFramework>
    <AssemblyName>RunicToolkit.Frontend.Sdk.Tests</AssemblyName>
    <RootNamespace>RunicToolkit.Frontend.Sdk.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
